[package]
name = "opentelemetry-tide"
version = "0.2.0"
authors = ["Christoph Grabo <asaaki@mannaz.cc>"]
edition = "2018"
readme = "README.md"
description = "OpenTelemetry integration for Tide"
homepage = "https://github.com/asaaki/opentelemetry-tide"
repository = "https://github.com/asaaki/opentelemetry-tide"
categories = [
  "development-tools::debugging",
  "development-tools::profiling",
  "asynchronous",
  "web-programming",
  "network-programming"
]
keywords = ["tide", "opentelemetry", "jaeger", "tracing", "instrumentation"]
license = "MIT OR Apache-2.0"
exclude = [
    ".github/*",
]

[dependencies]
opentelemetry = "0.7"
kv-log-macro = "1.0"
tide = "0.13"
http-types = "2.3"
url = "2.1"

[dev-dependencies]
async-std = {version =  "1.6", features = ["attributes"]}
femme = "2.1"
opentelemetry-jaeger = "0.6"
thrift = "0.13"
# pretty_assertions = "0.6.1"
